<%@ Page Language="C#" Title="Employees" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Employees.aspx.cs" Inherits="WebApplication.Employees.Employees" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="EmployeesGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="EmployeesGridView_RowCancelingEdit"
            OnRowDeleting="EmployeesGridView_RowDeleting"
            OnRowEditing="EmployeesGridView_RowEditing"
            OnRowUpdating="EmployeesGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="EmployeesGridView_PageIndexChanging"
            Caption="Employees" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="LastName" HeaderText="Last Name" SortExpression="LastName" />
                <asp:BoundField DataField="FirstName" HeaderText="First Name" SortExpression="FirstName" />
                <asp:BoundField DataField="MiddleName" HeaderText="Middle Name" SortExpression="MiddleName" />

                <asp:TemplateField HeaderText="Birth Date" SortExpression="BirthDate">
                    <EditItemTemplate>
                        <asp:Calendar ID="BirthDateDateCalendar" runat="server" SelectedDate='<%# Bind("BirthDate") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="BirthDate" runat="server" Text='<%# Eval("BirthDate") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Position" SortExpression="Position.Name">
                    <EditItemTemplate>
                        <asp:DropDownList ID="PositionsFieldDropDownList" DataSourceID="PositionsSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"  SelectedValue='<%# Bind("PositionId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="PositionId" runat="server" Text='<%# Eval("Position.Name") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

    </div>
   
    <div style="position:relative;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
       
        <h2>Add employee</h2>

        <div>
            <span>Last Name: </span>
            <asp:TextBox ID="EmployeeLastNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>First Name: </span>
            <asp:TextBox ID="EmployeeFirstNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Middle Name: </span>
            <asp:TextBox ID="EmployeeMiddleNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Birth Date: </span>
            <asp:Calendar ID="EmployeeBirthDatesCalendar" runat="server"></asp:Calendar>
        </div>

        <div>
            <span>Position: </span>
            <asp:DropDownList ID="PositionsDropDownList" DataSourceID="PositionsSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"></asp:DropDownList>
        </div>

        <div>
            <asp:Button ID="AddEmployeeButton" runat="server" Text="Add employee" OnClick="AddEmployeeButton_Click" />
        </div>
    </div>


    
    <asp:SqlDataSource ID="PositionsSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [Id], [Name] FROM [Positions]">
    </asp:SqlDataSource>
</asp:Content>
