<%@ Page Title="TypesOfRest" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="TypesOfRest.aspx.cs" Inherits="WebApplication.TypesOfRest.TypesOfRest" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="TypesOfRestGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="TypesOfRestGridView_RowCancelingEdit"
            OnRowDeleting="TypesOfRestGridView_RowDeleting"
            OnRowEditing="TypesOfRestGridView_RowEditing"
            OnRowUpdating="TypesOfRestGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="TypesOfRestGridView_PageIndexChanging"
            Caption="Types Of Rest" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:BoundField DataField="Limitation" HeaderText="Limitation" SortExpression="Limitation" />
            </Columns>
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add Type Of Rest</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="TypeOfRestNameTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Description: </span>
            <asp:TextBox ID="TypeOfRestDescriptionTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Limitation: </span>
            <asp:TextBox ID="TypeOfRestLimitationTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddTypeOfRestButton" runat="server" Text="Add type of rest" OnClick="AddTypeOfRestButton_Click" />
        </div>
    </div>
    
</asp:Content>
